stages:
    - build
    - deploy

image: node:11.4

cache:
  paths:
    - node_modules/
    - dist/

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy_staging:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p /var/www/web-starter
    - mkdir -p /etc/nginx/sites-enabled
    - cp nginx.dev.conf /etc/nginx/sites-enabled/web-starter
    - cp -r dist/* /var/www/web-starter/
    - sudo nginx -t
    - sudo /etc/init.d/nginx reload
  environment:
    name: staging
    url: https://web-starter.stg.xvrqt.com
  only:
  - master
  
deploy_production:
  stage: deploy
  tags:
    - shell
  script:
    - scp -p nginx.prod.conf root@static-01:/etc/nginx/sites-enabled/web-starter
    - scp -pr dist root@static-01:/var/www/web-starter
    - ssh root@static-01 'nginx -t && service nginx reload'
  environment:
    name: production
    url: https://web-starter.xvrqt.com
  when: manual
  only:
    - tags
