version: '3'

services:
  ts-web-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app/
    ports:
      - 2222:80

  ts-web-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 80:80
    depends_on:
      - ts-web-app-dev